### PR TITLE
Fix syntax to partially comply PEP8

### PR DESCRIPTION
**Pull request by dmitry-guryanov**

### CODE REVIEW

**Comment by avagin** [comment]
Can you fix .travis.yaml to run flake8?

**Comment by avagin** [comment]
@xemul could you activate travis for this repo?

**Comment by xemul** [comment]
@avagin, should have been activated.

**Comment by avagin** [comment]
https://travis-ci.org/xemul/p.haul

No builds for this repository

Want to start testing this project on Travis CI?

Read the Docs on Getting Started

**Comment by xemul** [comment]
I don't get you. Travis.yml is there, repo is ON on travis side. Travis says that it builds on pushes and on pull requrests. I've turned it all on after merged the last PR, so what builds do you expect?

**Pull request merged**
